### ISSUE TITLE
attributeFields, defaultArgs and defaultListArgs input type getting error

### ISSUE THREAD

**Issue by blueorbitz** [mickhansen/graphql-sequelize#115]
I been looking every where for a solution for this, and couldn't find any. Can anyone help me with this?

All I did was trying to test out this few functions
`attributeFields` and `defaultArgs` and `defaultListArgs`.

as below
```javascript
let taskType = new GraphQLObjectType({
  name: 'Task',
  description: 'A task',
  fields: _.assign(attributeFields(Task))
});

let userType = new GraphQLObjectType({
  name: 'User',
  description: 'A user',
  fields: _.assign(attributeFields(User))
});
```

and also

```javascript
let schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'RootQueryType',
    fields: {
      user: {
        type: userType,
        // args will automatically be mapped to `where`
        args: _.assign(defaultArgs(User), {
          firstName: {type: GraphQLString}
        }),
        resolve: resolver(User)
      },
      users: {
        // The resolver will use `findOne` or `findAll` depending on whether the field it's used in is a `GraphQLList` or not.
        type: new GraphQLList(userType),
        args: _.assign(defaultListArgs()),
        resolve: resolver(User)
      }
    }
  })
});
```

but I am getting error as below.
```
    throw new Error(message);
          ^
Error: RootQueryType.user(id:) argument type must be Input Type but got: Int!.
    at invariant (C:\Users\HomePC\Documents\JSWorkspace\orm-testing\node_modules\graphql\jsutils\invariant.js:20:11)
    at C:\Users\HomePC\Documents\JSWorkspace\orm-testing\node_modules\graphql\type\definition.js:307:43
    at Array.map (native)
    at C:\Users\HomePC\Documents\JSWorkspace\orm-testing\node_modules\graphql\type\definition.js:304:45
    at Array.forEach (native)
    at defineFieldMap (C:\Users\HomePC\Documents\JSWorkspace\orm-testing\node_modules\graphql\type\definition.js:293:14)
    at GraphQLObjectType.getFields (C:\Users\HomePC\Documents\JSWorkspace\orm-testing\node_modules\graphql\type\definition.js:247:46)
    at typeMapReducer (C:\Users\HomePC\Documents\JSWorkspace\orm-testing\node_modules\graphql\type\schema.js:173:27)
    at Array.reduce (native)
    at new GraphQLSchema (C:\Users\HomePC\Documents\JSWorkspace\orm-testing\node_modules\graphql\type\schema.js:81:120)
    at Object.<anonymous> (C:\Users\HomePC\Documents\JSWorkspace\orm-testing\sequelize.js:103:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (C:\Users\HomePC\AppData\Roaming\npm\node_modules\traceur-runner\node_modules\traceur\src\node\require.js:68:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
17 Jan 00:48:04 - [nodemon] app crashed - waiting for file changes before starting...
```

It work fine, if I were to replace it to call directly on the GraphQL Type.

```javascript
let taskType = new GraphQLObjectType({
  name: 'Task',
  description: 'A task',
  fields: {
    id: {
      type: new GraphQLNonNull(GraphQLInt),
      description: 'The id of the task.',
    },
    title: {
      type: GraphQLString,
      description: 'The title of the task.',
    }
  }
});

let userType = new GraphQLObjectType({
  name: 'User',
  description: 'A user',
  fields: {
    id: {
      type: new GraphQLNonNull(GraphQLInt),
      description: 'The id of the user.',
    },
    firstName: {
      type: GraphQLString,
      description: 'The name of the user.',
    },
    lastName: {
      type: GraphQLString,
      description: 'The name of the user.',
    },
    tasks: {
      type: new GraphQLList(taskType),
      resolve: resolver(User.Tasks)
    },
  }
});

let schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'RootQueryType',
    fields: {
      user: {
        type: userType,
        // args will automatically be mapped to `where`
        args: {
          id: {
            description: 'id of the user',
            type: new GraphQLNonNull(GraphQLInt)
          }
        },
        resolve: resolver(User)
      },
      users: {
        // The resolver will use `findOne` or `findAll` depending on whether the field it's used in is a `GraphQLList` or not.
        type: new GraphQLList(userType),
        args: {
          // An arg with the key limit will automatically be converted to a limit on the target
          limit: {
            type: GraphQLInt
          },
          // An arg with the key order will automatically be converted to a order on the target
          order: {
            type: GraphQLString
          }
        },
        resolve: resolver(User)
      }
    }
  })
});
```
Any idea how to fix this?

**Comment by mickhansen** [comment]
Do you have multiple versions of GraphQL installed?
It should just work, but i haven't actually used defaultArgs myself in a while.

**Comment by blueorbitz** [comment]
Both my project and graphql-sequalize are using graphql version 0.4.14. I am using NodeJS v4.2.4.
I have tried using just es5, also having the same error.

Any suggestion what else I can try?

**Comment by mickhansen** [comment]
Really not sure, you can try inspecting whats returned from defaultArgs

**Comment by blueorbitz** [comment]
Hmm.. So happen I tested on other machine. Is working. Both are using the same version of NodeJS. I'll try to look into my other machine and see what causing it to fail.

**Comment by blueorbitz** [comment]
I am closing this ticket. I did a clean npm install again and solve the problem.
Thanks for the support Mick.
