### ISSUE TITLE
Feature proposal: default attributes

### ISSUE THREAD

**Issue by jonathanewerner** [mickhansen/graphql-sequelize#172]
Hi,
I have the following problem: For validating permission / access to resources, we need to *always* fetch an owner id like `userId` on the requested instance. This should happen without the need to explicitly require the field in a query.
 
So for example I'd like to be able to say `{ orders(userId: "12375") { id } }`, which should set `findOptions.attributes` to `['userId', 'id']`. This would allow me to a) not overfetch SQL columns and b) to not force the expose unwanted information in the response.

**Comment by mickhansen** [comment]
I had to disable attribute filtering personally because there was always fields i needed that wasn't explicitely requested by the graphql query.

**Comment by jonathanewerner** [comment]
Does that mean that you think that `filterAttributes` = `false` is the way to go here or do you think a resolver option like `defaultAttributes` would make sense?

**Comment by mickhansen** [comment]
That's the work around for now atleast. I like the idea of defaultAttributes though.

**Comment by jonathanewerner** [comment]
I could take a stab at a PR for that if you'd like.

**Comment by mickhansen** [comment]
Sure, please do

**Comment by jonathanewerner** [comment]
I'm trying to get started with dev setup. 
I get test failures when executing `npm run test-docker`:
```
  1) relay connection should support prefetching two nested connections:

      AssertionError: expected 'CAA' to equal 'CCC'
      + expected - actual

      -CAA
      +CCC
      
      at Context.<anonymous> (test/integration/relay/connection.test.js:665:85)
      at [object Generator].next (native)
      at [object Generator].tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:90:49)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:565:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:605:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:684:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:126:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:136:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:16:14)

```
This test sometimes fails, sometimes not.
On first sight it seems that `expect(result.data.user.projects.edges[1].node.tasks.edges[2].node.name).to.equal('CCC');` expects the data to be in a specific order which is not actually guaranteed?

When i skip this test, i get other failures:
```
  1) relay should support first queries on connections:

      AssertionError: expected { Object (user) } to deeply equal { Object (user) }
      + expected - actual

           "tasks": {
             "edges": [
               {
                 "node": {
      -            "name": "0.5536965578794479"
      +            "name": "0.7577085853554308"
                 }
               }
             ]
           }
      
      at [object Object].assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at [object Object].ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
      at [object Object].<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:251:21)
      at [object Object].ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at test/integration/relay.test.js:313:35
      at run (node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:104:47)
      at node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:115:28
      at flush (node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:19:5)

  2) relay should support last queries on connections:

      AssertionError: expected { Object (user) } to deeply equal { Object (user) }
      + expected - actual

           "tasks": {
             "edges": [
               {
                 "node": {
      -            "name": "0.7577085853554308"
      +            "name": "0.5536965578794479"
                 }
               }
             ]
           }
      
      at [object Object].assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at [object Object].ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
      at [object Object].<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:251:21)
      at [object Object].ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at test/integration/relay.test.js:349:35
      at run (node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:104:47)
      at node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:115:28
      at flush (node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:19:5)

  3) relay should resolve a plain result with a single connection:

      AssertionError: expected { Object (user) } to deeply equal { Object (user) }
      + expected - actual

           "tasks": {
             "edges": [
               {
                 "node": {
      -            "name": "0.5536965578794479"
      +            "name": "0.7577085853554308"
                 }
               }
               {
                 "node": {
      -            "name": "0.7577085853554308"
      +            "name": "0.5536965578794479"
                 }
               }
             ]
           }
      
      at [object Object].assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at [object Object].ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
      at [object Object].<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:251:21)
      at [object Object].ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at test/integration/relay.test.js:428:35
      at run (node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:104:47)
      at node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:115:28
      at flush (node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:19:5)

```

So my question is: is there sth wrong with my setup or can you reproduce those test failures?

**Comment by mickhansen** [comment]
There are a few flaky tests i've been too lazy to fix proper.

**Comment by jonathanewerner** [comment]
K ill try to fix them when I find the time.
