### ISSUE TITLE
Mutations Implementation

### ISSUE THREAD

**Issue by ChiefORZ** [mickhansen/graphql-sequelize#180]
Hey there!
I love the simplicity of this module and the speed on how i've done my whole Queries!

But now i'm stuck with Mutations...

I've implemented the Mutation manually, because i haven't seen any implementation example provided in the Readme.
```js
  addPost: {
    type: PostType,
    args: {
      post: {type: new GraphQLNonNull(NewPost)}
    },
    resolve: (root, { post }, { rootValue }) => {
      return new Promise((resolve, reject) => {
        post.uuid = uuid.v4();
        Post
          .create(post)
          .then((model) => {
            resolve(model.get({
              plain: true
            }));
          }).catch((err) => {
            reject(err);
          });
      });
    }
  },
```
It works great - the Row gets inserted and the Post gets returned as intended.

But as soon as i pass a Child Query like `user ` in the snippet below, i get a `null` on the user attribute and the error **source.get is not a function**
```js
mutation {
  addPost(post: {
    userId: 2,
    name: "Test"
  }) {
    uuid
    name
    createdAt
    updatedAt
    user {
      firstName
      lastName
    }
  }
}
```

Does someone know what i am doing incorrect?
Or does someone has an example of how to sucessfully mutate when sequelize is the orm for the queries?

**Comment by mickhansen** [comment]
First of all why are you wrapping sequelize promises in another promise?
It doesn't look like you're using the relay spec for mutations, however that shouldn't matter.

The problem is that you're resolving a plain POJO and not an instance, however since you're requesting an association we expect to be working with an instance. Change the resolver to simply return the instance rather than the plain values.

**Comment by bringking** [comment]
@ChiefORZ if you want to resolve associations then you would need to use the `resolver` for your model, so you are returning a GraphQLType and not a POJO. In this case, I would try something like this -

```js
import {resolver} from 'graphql-sequelize';

// create a resolver for your post model
let resolverFn = resolver(PostModel)

 addPost: {
    type: PostType,
    args: {
      post: {type: new GraphQLNonNull(NewPost)}
    },
    resolve: (root, { post }, info) => {

       
        post.uuid = uuid.v4();

        return Post
          .create(post)
          .then((model) => {
           return resolveFn(root,{uuid:post.uuid},info)
          }).catch((err) => {
            return Promise.reject(err);
          });

    }
  }
```

Note this isn't tested.. But something along these lines should work

**Comment by bringking** [comment]
@ChiefORZ Did this help answer your question? If so, can you close this issue?

**Comment by ChiefORZ** [comment]
@bringking i just tried it out and it works flawlessly! the answer of you two was great! Big thanks for the help!

**Comment by amirklick** [comment]
@bringking Hey. I'm writing a mutation query that creates a video. This query should also setup associations. Assume videos and events have a many-to-many association. The event already exists. Based on the docs, the following is how I've managed to make it happen. Is there a better way like using the resolver?

```
import {
  GraphQLString as StringType,
  GraphQLNonNull as NonNull,
  GraphQLInt as IntType,
  GraphQLBoolean as BooleanType,
} from 'graphql';

import VideoType from '../../types/VideoType';
import Video from '../../models/Video';

const createVideo = {
  type: VideoType,
  args: {
    id: {
      type: new NonNull(StringType),
    },
    title: {
      type: new NonNull(StringType),
    },
    description: {
      type: new NonNull(StringType),
    },
    duration: {
      type: new NonNull(IntType),
    },
    isEspresso: {
      type: new NonNull(BooleanType),
    },
    image_urls: {
      type: new NonNull(StringType),
    },
    url: {
      type: new NonNull(StringType),
    },
    event: {
      type: new NonNull(StringType),
    },
    tags: {
      type: new NonNull(StringType),
    },
  },
  resolve: (_, args) => (
    Video.create({ ...args })
      .then(video => (
        Promise.all([
          video.setEvents([args.event]),
          video.setTags(args.tags.split(',')),
        ]).then(() => video)
      ))
  ),
};

export default createVideo;
```

**Comment by pbrink231** [comment]
It would be very helpful to add this to the Readme.  mutation examples with sequelize are scarce.  I learned a lot just from your readme.

**Comment by pbrink231** [comment]
hi @mickhansen I hope you could help me with this:

```
     let resolverFn = resolver(db.Account)
    updateAccount: {
      type: accountType,
      description: 'Update account properties',
      args: {
        id: {
          type: new GraphQLNonNull(GraphQLString)
        },
        account: {
          type: new GraphQLNonNull(accountInput)
        }
      },
      resolve: (root, { id, account }, info) => {
        db.Account.findById(id).then(foundAccount => {
          if (!foundAccount) {
            throw new UserError('account not found');
          } else {
            foundAccount.update(account).then((model) => {
              return resolverFn(root, { id: id }, info)
            }).catch((err) => {
              return Promise.reject(err);
            });;
          }
        });
      }
    },
```

I am getting this error:
```
Unhandled rejection TypeError: Cannot read property 'returnType' of undefined
    at C:\source\repos\isotime\node_modules\graphql-sequelize\lib\resolver.js:54:23
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\source\repos\isotime\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\source\repos\isotime\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\source\repos\isotime\node_modules\bluebird\js\release\generators.js:201:15
    at C:\source\repos\isotime\node_modules\graphql-sequelize\lib\resolver.js:118:19
    at foundAccount.update.then (C:\source\repos\isotime\db\schema.js:354:22)
```

I know the account is found but I cant seem to get this to work quite right.  Would be great.  BTW great module which is fantastic for the query part.

**Comment by mickhansen** [comment]
Where are you return types for the mutation defined?

**Comment by pbrink231** [comment]
here is the accountType:
```
//Define Order type
const accountType = new GraphQLObjectType({
  name: 'Account',
  description: 'An account',
  fields: {
    id: {
      type: new GraphQLNonNull(GraphQLInt),
      description: 'The id of the account.'
    },
    name: {
      type: new GraphQLNonNull(GraphQLString),
      description: 'Name of the account.'
    },
    .... // more fields
    shipping_country: {
      type: GraphQLString,
      description: 'Shipping Country of the account.'
    }
  }
})
```
And this is the mutation query:
```
mutation updateAccount($id: String!, $input: accountInput!) {
  updateAccount(id: $id, account: $input) {
    name
    email
  }
}

{
  "id": "4",
  "input": {
    "name": "hopefusdflly last test",
    "email": "graphy@ql.com",
    "primary_contact": "Graph QL",
    "billing_state": "Georgia"
  }
}
```

Is that what you were asking for.

**Comment by mickhansen** [comment]
It wasn't, i meant where are you defining your mutation output.

**Comment by pbrink231** [comment]
I am using graphql yes.  The above updateAccount is the query.  here is more the file

```
const { resolver } = require('graphql-sequelize');
const { UserError } = require('graphql-errors')
const { GraphQLSchema, GraphQLObjectType, GraphQLString, GraphQLInt, GraphQLNonNull, GraphQLList, GraphQLInputObjectType } = require('graphql');
const db = require('./models');
const { accountInput } = require('./schemaTypes');

const accountType = ... (shown in previous post above)

var MutationType = new GraphQLObjectType({
  name: 'Mutations',
  description: 'These are the things we can change',
  fields: () => ({
    createAccount: {
      type: accountType,
      description: 'Create a new account',
      args: {
        account: {
          type: new GraphQLNonNull(accountInput)
        }
      },
      resolve: (value, { account }) => {
        return db.Account.create(account);
      }
    },
    updateAccount: {
      type: accountType,
      description: 'Update account properties',
      args: {
        id: {
          type: new GraphQLNonNull(GraphQLString)
        },
        account: {
          type: new GraphQLNonNull(accountInput)
        }
      },
      resolve: (root, { id, account }, info) => {
        return db.Account.findById(id).then(foundAccount => {
          if (!foundAccount) {
            throw new UserError('account not found');
          } else {
            foundAccount.update(account).then((model) => {
              resolverFn(root, { id: id }, info)
            }).catch((err) => {
              Promise.reject(err);
            });;
          }
        });
      }
    },
    deleteAccount: {
      type: accountType,
      description: 'Delete an account with id and return the article that was deleted.',
      args: {
        id: {
          type: new GraphQLNonNull(GraphQLInt)
        }
      },
      resolve: (value, { id }) => {
        return db.Account.destroy(id);
      }
    },
  }),
});
```

This is the graphql input item: 
```
const { GraphQLSchema, GraphQLObjectType, GraphQLString, GraphQLInt, GraphQLNonNull, GraphQLList, GraphQLInputObjectType } = require('graphql')

module.exports = new GraphQLInputObjectType({
  name: 'accountInput',
  description: 'Input account payload',
  fields: () => ({
    name: {
      type: new GraphQLNonNull(GraphQLString),
    },
    ...... More fields here condensed for easier reading 
    shipping_country: {
      type: GraphQLString,
      description: 'Shipping Country of the account.'
    }
  })
});
```

I am able to accomplish the mutations but working on getting the correct information returned.  I feel your resolver is still needed because technically a mutation is still a query just with an action first.  Thank you for the help, I really appreciate it.

**Comment by pellejacobs** [comment]
@mickhansen Love the library. Is there any reason you haven't implemented a `mutation` helper, similar to the `resolver` helper? It would help a lot to implement the remaining CRUD actions.

**Comment by mickhansen** [comment]
@pellejacobs mostly just haven't seen a good reason or thought of a good design for it.
