### ISSUE TITLE
Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by negezor** [mickhansen/graphql-sequelize#549]
Does not work relay connection. I implement the search, but something obviously went wrong.
Stack trace
```js
TypeError: Cannot read property 'node' of undefined
    at nodeType (C:\Users\negezor\node\shiza\node_modules\graphql-sequelize\lib\relay.js:114:59)
    at resolver (C:\Users\negezor\node\shiza\node_modules\graphql-sequelize\lib\resolver.js:75:34)
    at resolver (C:\Users\negezor\node\shiza\node_modules\graphql-sequelize\lib\relay.js:378:14)
    at search (C:\Users\negezor\node\shiza\lib\server\graphql\resolvers\search.js:143:26)
    at resolveFieldValueOrError (C:\Users\negezor\node\shiza\node_modules\graphql\execution\execute.js:498:12)
    at resolveField (C:\Users\negezor\node\shiza\node_modules\graphql\execution\execute.js:462:16)
    at C:\Users\negezor\node\shiza\node_modules\graphql\execution\execute.js:311:18
    at Array.reduce (<anonymous>)
    at executeFields (C:\Users\negezor\node\shiza\node_modules\graphql\execution\execute.js:308:42)
    at executeOperation (C:\Users\negezor\node\shiza\node_modules\graphql\execution\execute.js:236:122)
    at executeImpl (C:\Users\negezor\node\shiza\node_modules\graphql\execution\execute.js:133:26)
    at Object.execute (C:\Users\negezor\node\shiza\node_modules\graphql\execution\execute.js:110:229)
    at doRunQuery (C:\Users\negezor\node\shiza\node_modules\apollo-server-core\dist\runQuery.js:98:26)
    at C:\Users\negezor\node\shiza\node_modules\apollo-server-core\dist\runQuery.js:22:54
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
Create connection
```js
const { resolve: releaseConnection } = relay.sequelizeConnection({
	name: 'releases',
	target: Release,

	where(key, value) {
		return {
			[key]: value
		};
	},

	before(options, { query }, context) {
		options.where = {
			name: {
				[Op.iLike]: `%${query}%`
			},
			[Op.or]: [
				{
					japanese: {
						[Op.iLike]: `%${query}%`
					}
				},
				{
					synonyms: {
						[Op.iLike]: `%${query}%`
					}
				},
			]
		};

		return options;
	}
});

const { resolve: communityConnection } = relay.sequelizeConnection({
	name: 'communities',
	target: Community,

	where(key, value) {
		return {
			[key]: value
		};
	},

	before(options, { query }, context) {
		options.where = {
			name: {
				[Op.iLike]: `%${query}%`
			}
		};

		return options;
	}
});

const { resolve: userConnection } = relay.sequelizeConnection({
	name: 'users',
	target: User,

	where(key, value) {
		return {
			[key]: value
		};
	},

	before(options, { query }, context) {
		options.where = {
			name: {
				[Op.iLike]: `%${query}%`
			}
		};

		return options;
	}
});
```
Query resolver
```js
Query: {
	async search(...args) {
		const { type } = args[1];

		if (type === 'RELEASE') {
			return await releaseConnection(...args);
		} else if (type === 'COMMUNITY') {
			return await communityConnection(...args);
		}

		return await userConnection(...args);
	}
}
```
Schema search
```graphql
enum SearchType {
	RELEASE
	COMMUNITY
	USER
}

union SearchUnion = Release | Community | User

type SearchEdge {
	cursor: String!
	node: SearchUnion!
}

type SearchConnection {
	totalCount: Int!

	edges: [SearchEdge!]!

	pageInfo: PageInfo!
}

type Query {
	search(
		first: Int = 10,
		after: String,

		last: Int,
		before: String,

		query: String!,
		type: SearchType!
	): SearchConnection
}
```
## Versions

Node.js: **9.2.0**

sequelize: **4.23.1**

graphql: **0.11.7**
graphql-relay: **0.5.3**
graphql-tools: **2.8.0**
graphql-sequelize: **5.6.0**

**Comment by mickhansen** [comment]
https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L102

You're not including your query but looks like you might be getting edges without nodes?

**Comment by negezor** [comment]
Yes, edges can be empty. My query
```graphql
query {
  search(type: USER, query: "nege") {
    edges {
      node {
        ... on User {
          id
          name
        }
      }
    }
  }
}
```

**Comment by mcurcio** [comment]
I hit on a similar issue recently. I think the latest Sequelize is incompatible with graphql-sequelize. I think the change happened around v4.9 ( I reverted to sequelize v4.8.4 and the issue went away).

**Comment by mickhansen** [comment]
@negezor The edge is not empty in that query though
