### ISSUE TITLE
[Help] How To integrate dataloader-sequelize

### ISSUE THREAD

**Issue by mubaidr** [mickhansen/graphql-sequelize#645]
There are conflicting documentation by both repositories on how to integrate `dataloader-sequelize` with `graphql-sequelize`. 

I tried following the example project `graphql-yoga`, but there is an error when running any query:
```bash
TypeError: Cannot read property 'findById' of undefined
    at shimModel (D:\Current\ors-node\api\node_modules\dataloader-sequelize\lib\index.js:281:14)
    at createContext (D:\Current\ors-node\api\node_modules\dataloader-sequelize\lib\index.js:526:3)
    at GraphQLServer.context (D:\Current\ors-node\api\index.js:21:31)
    at GraphQLServer.<anonymous> (D:\Current\ors-node\api\node_modules\graphql-yoga\dist\index.js:231:51)
    at step (D:\Current\ors-node\api\node_modules\graphql-yoga\dist\index.js:43:23)
    at Object.next (D:\Current\ors-node\api\node_modules\graphql-yoga\dist\index.js:24:53)
    at D:\Current\ors-node\api\node_modules\graphql-yoga\dist\index.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Current\ors-node\api\node_modules\graphql-yoga\dist\index.js:14:12)
    at D:\Current\ors-node\api\node_modules\graphql-yoga\dist\index.js:224:118
    at D:\Current\ors-node\api\node_modules\apollo-server-core\dist\graphqlOptions.js:52:40
    at step (D:\Current\ors-node\api\node_modules\apollo-server-core\dist\graphqlOptions.js:32:23)
    at Object.next (D:\Current\ors-node\api\node_modules\apollo-server-core\dist\graphqlOptions.js:13:53)
    at D:\Current\ors-node\api\node_modules\apollo-server-core\dist\graphqlOptions.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Current\ors-node\api\node_modules\apollo-server-core\dist\graphqlOptions.js:3:12)
    at resolveGraphqlOptions (D:\Current\ors-node\api\node_modules\apollo-server-core\dist\graphqlOptions.js:43:12)
    at Object.<anonymous> (D:\Current\ors-node\api\node_modules\apollo-server-core\dist\runHttpQuery.js:79:71)
    at step (D:\Current\ors-node\api\node_modules\apollo-server-core\dist\runHttpQuery.js:42:23)
    at Object.next (D:\Current\ors-node\api\node_modules\apollo-server-core\dist\runHttpQuery.js:23:53)
    at D:\Current\ors-node\api\node_modules\apollo-server-core\dist\runHttpQuery.js:17:71
    at new Promise (<anonymous>)
```

and response from query: 
```bash
Invalid options provided to ApolloServer: Cannot read property 'findById' of undefined
```

Server starting file: https://github.com/mubaidr/ors-node-graphql.js/blob/master/api/index.js#L21

GraphQl schema loading code: https://github.com/mubaidr/ors-node-graphql.js/blob/master/api/db/graphQl.js#L19

Can somebody guide me how to do it?

**Comment by mickhansen** [comment]
Your setup looks correct.
It's failing in the shimModel code which is odd, apparently it's being passed an undefined Model, my best guess is one of your associations is defined incorrectly

**Comment by mickhansen** [comment]
Hmm actually, looking at the line of code likely being hit here: https://github.com/mickhansen/dataloader-sequelize/blob/master/src/index.js#L474

What version of Sequelize are you using?

**Comment by mubaidr** [comment]
Ohh. Right now its on v5 beta. 

I will test this with v4 and will report back. Thanks

**Comment by mickhansen** [comment]
It should work for v5 too, looking at the code, but i'm personally still on v3 so

**Comment by mubaidr** [comment]
@mickhansen Yup, that was it, sorry to bother you. Downgraded to v4; graphql api now seems to work. and I can confirm that `dataloader-sequelize` is working too, there is some noticeable difference in response time for nested query. 

Thanks for your awesome work and support. 👍

**Comment by mickhansen** [comment]
I'd appreciate if you could test why that regex doesn't work @mubaidr and potentially provide a fix :)

**Comment by mubaidr** [comment]
Hmm Will try that. 👍
